development:
  cl_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cl_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cl_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
test:
  cl_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cl_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cl_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
production:
  cl_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cl_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cl_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
